version: 2.1

jobs:
  build:
    docker:
        - image: circleci/openjdk:8-stretch

    environment:
        MAVEN_OPTS: "-Xms512m -Xmx512m -Xss10M"

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn validate
      - run: mvn test

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

  release:
    docker:
      - image: circleci/openjdk:8-stretch
    working_directory: /tmp
    
    environment:
        MAVEN_OPTS: "-Xms512m -Xmx512m -Xss10M"

    steps:
      - checkout
      
      - run:
          name: package datashare dataconnect extension
          command: mvn package > mvn.out
      - persist_to_workspace:
          root: /tmp
          paths:
           - datashare-dataconnect-extension
      - run:
          name: deploy datashare dataconnect extension jar to github release
          command: |
            upload_url=$(curl -s -H "Authorization: token $GITHUB_TOKEN" -d "{\"tag_name\":\"${CIRCLE_TAG}\", \"name\":\"${CIRCLE_TAG}\",\"body\":\"release ${CIRCLE_TAG}\"}" "https://api.github.com/repos/ICIJ/datashare-extension-dataconnect/releases" | jq -r '.upload_url')
            upload_url="${upload_url%\{*}"
            echo "uploading asset to release url: $upload_url"
            curl -s -m 120 -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/java-archive" --data-binary "@/tmp/datashare-dataconnect-extension/target/datashare-dataconnect-${CIRCLE_TAG}-jar-with-dependencies.jar" "$upload_url?name=datashare-dataconnect-${CIRCLE_TAG}-jar-with-dependencies.jar&label=datashare-dataconnect-${CIRCLE_TAG}-jar-with-dependencies.jar"

workflows:
  version: 2
  build_workflow:
    jobs:
      - build:
          filters:
              tags:
                  only: /.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^[0-9.]*/
            branches:
              ignore: /.*/
