version: 2.1

jobs:
  build:
    docker:
        - image: circleci/openjdk:8-stretch

    environment:
        MAVEN_OPTS: "-Xms512m -Xmx512m -Xss10M"

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn validate
      - run: mvn test

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
